language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script:
  - python -m  unittest discover -s  Tests
  - pytest --cov=statsCalculator
after_success:
  - coveralls