language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script:
  - python -m  unittest discover -s Tests
branches:
  only:
    - master
after_success:
  - coveralls