language: python
python:
  - "3.7"
script:
  - python -m  unittest discover -s  Tests
  - pip install coveralls coverage run --source=mypkg -m pytest tests/
    coveralls

branches:
  only:
    - master
after_success:
  - coveralls